apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev-ns
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        env: dev
    spec:
      containers:
      - name: web
        image: nginx:1.14.2
        ports:
        - containerPort: 80
