apiVersion: v1
kind: ReplicationController
metadata:
  name: static-web
  namespace: dev-ns
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    name: web
  template:
    metadata:
      name: nginx
      labels:
        name: web
        env: dev
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
