apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: dev-ns
  labels:
    role: web
    env: dev
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP